export const decks = [
  'AAEBAfHhBAHS4gQAAAA=',
  'AAEBAea5AwHmuQMAAAA=',
  'AAEBAZICAZICAAAA',
  'AAEBAR8BHwAAAA==',
  'AAEBAf0EAf0EAAAA',
  'AAEBAZ8FAZ8FAAAA',
  'AAEBAa0GHooHywjTCtcK8uwC4/cC9/wCoIADl4cD5ogDgpQDjZcDmJsD65sDoaEDpaED/KMD0aUDhKcDmakDn6kD2qwD8qwDha0D/q4Dza8DjrEDkbED47QDyMADAAAA',
  'AAEBAaIHAaIHAAAA',
  'AAEBAaoIAaoIAAAA',
  'AAEBAf0GAf0GAAAA',
  'AAEBAQcBBwAAAA==',
];
